
Error 2020 (..\.\tmpNativo_2.txt, line 81):
    VK_'I' (49) found at scancode 27 and 17.


Error 2020 (..\.\tmpNativo_2.txt, line 81):
    VK_'I' (49) found at scancode 27 and 17.


Error 2020 (..\.\tmpNativo_2.txt, line 81):
    VK_'I' (49) found at scancode 27 and 17.


Error 2020 (..\.\tmpNativo_2.txt, line 81):
    VK_'I' (49) found at scancode 27 and 17.

